const {chromium}=require('/opt/node22/lib/node_modules/playwright');
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});const pg=await (await b.newContext({viewport:{width:480,height:800}})).newPage();await pg.addInitScript(()=>{try{localStorage.setItem("mode","full")}catch(e){}});const errs=[],bad=[];
pg.on('pageerror',e=>errs.push(e.message));pg.on('dialog',d=>d.dismiss());
await pg.goto('http://127.0.0.1:'+process.argv[2]+'/',{waitUntil:'domcontentloaded'});await pg.waitForTimeout(600);
if(await pg.$('#ackbox')){await pg.check('#ackbox');await pg.click('#ackgo')}
await pg.click('.tab[data-tab="guided"]');await pg.waitForTimeout(300);
await pg.evaluate(()=>{FOLDERS.length=0;saveFolders();document.getElementById('fdest').value='';saveDest()});
const vis=id=>pg.evaluate(i=>{const e=document.getElementById(i);return !!(e&&e.offsetParent!==null)},id);
if(!/Add your photos/.test(await pg.locator('#fsum').innerText()))bad.push('empty prompt missing with no sources');
let t=await pg.evaluate(()=>document.getElementById('rtstat').textContent);if(t!=='')bad.push('status should be empty: '+t);
await pg.evaluate(()=>addFolders(['/tmp/a','/tmp/b','/tmp/c','/tmp/d','/tmp/e.zip']));
const sm=await pg.locator('#fsum').innerText();if(!/4 folders \+ 1 zip/.test(sm))bad.push('summary '+sm);
if(/Add your photos/.test(await pg.locator('#fsum').innerText()))bad.push('empty prompt shown with sources');
await pg.click('[data-tab=guided]');if(!(await vis('frd')))bad.push('TO hidden on guided');
t=await pg.evaluate(()=>document.getElementById('rtstat').textContent);if(!/choose where to save/i.test(t))bad.push('guided status: '+t);
await pg.click('[data-tab=health]');if(await vis('frd'))bad.push('TO visible on health');
await pg.click('[data-tab=history]');if(await vis('fbar'))bad.push('route visible on history');
await pg.click('[data-tab=merge]');if(!(await vis('frd')))bad.push('TO hidden on merge');
await pg.evaluate(()=>{document.getElementById('fdest').value='/tmp/zz';saveDest()});
const rec=await pg.evaluate(()=>document.getElementById('recentdest').innerHTML);if(!/zz/.test(rec))bad.push('recent not saved');
console.log(JSON.stringify({bad,errs}));await b.close()})();
